apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      name: webserver-pod
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        image: httpd:latest
        env:
        - name: HTTPD_HOME
          value: "/var/www/html"
        ports:
        - containerPort: 88
